#!/usr/bin/env bash
set -euo pipefail

GH_USER="${GH_USER:-oleg-koval}"
OUTPUT="${1:-README.md}"

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh CLI is required to rebuild the starter index" >&2
  exit 127
fi

echo "→ Fetching template repos for $GH_USER..."

# ponytail: modern gh rejects --slurp combined with --jq, so pipe to jq instead
REPOS=$(gh api graphql --paginate --slurp -f login="$GH_USER" -f query='
query($login: String!, $endCursor: String) {
  user(login: $login) {
    repositories(first: 100, after: $endCursor, orderBy: {field: UPDATED_AT, direction: DESC}) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        name
        description
        url
        isTemplate
        updatedAt
        repositoryTopics(first: 10) {
          nodes { topic { name } }
        }
        primaryLanguage { name }
        stargazerCount
      }
    }
  }
}
' | jq '
  [.[].data.user.repositories.nodes[]]
  | map(select(.isTemplate == true))
  | sort_by(.updatedAt)
  | reverse
')

COUNT=$(echo "$REPOS" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")
echo "  Found $COUNT template repos"

python3 - "$REPOS" "$GH_USER" "$OUTPUT" <<'PYEOF'
import datetime
import html
import json
import sys
from collections import defaultdict

repos_json, gh_user, output_path = sys.argv[1], sys.argv[2], sys.argv[3]
repos = json.loads(repos_json)
now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")

def md_cell(value):
    text = html.escape(str(value or ""), quote=False)
    return text.replace("|", "\\|").replace("\n", " ")

LANG_EMOJI = {
    "TypeScript": "🔷",
    "JavaScript": "🟨",
    "Python":     "🐍",
    "Go":         "🐹",
    "Rust":       "🦀",
    "Shell":      "🐚",
    "YAML":       "⚙️",
}

lines = []
lines.append(f"# starters\n")
lines.append(f"> Auto-generated index of [@{gh_user}](https://github.com/{gh_user}) template repositories.\n")
lines.append(f"> Last updated: {now} · [{len(repos)} templates found](https://github.com/{gh_user}?tab=repositories&q=&type=template)\n")
lines.append("")
lines.append("## Templates\n")

by_lang = defaultdict(list)
for r in repos:
    lang = r.get("primaryLanguage") or {}
    lang_name = lang.get("name") or "Other"
    by_lang[lang_name].append(r)

LANG_ORDER = ["TypeScript", "JavaScript", "Go", "Python", "Rust", "Shell", "YAML", "Other"]
sorted_langs = sorted(by_lang.keys(), key=lambda l: (LANG_ORDER.index(l) if l in LANG_ORDER else len(LANG_ORDER), l))

for lang in sorted_langs:
    emoji = LANG_EMOJI.get(lang, "📦")
    lines.append(f"### {emoji} {lang}\n")
    lines.append("| Repo | Description | Topics | Stars | CI |")
    lines.append("|------|-------------|--------|-------|-----|")
    for r in by_lang[lang]:
        name = md_cell(r["name"])
        desc = md_cell(r.get("description"))
        url = r["url"]
        stars = r.get("stargazerCount", 0)
        topics = [md_cell(t["topic"]["name"]) for t in r.get("repositoryTopics", {}).get("nodes", [])]
        topic_badges = " ".join([f"`{t}`" for t in topics]) if topics else "-"
        ci = f"[![ci]({url}/actions/workflows/ci.yml/badge.svg)]({url}/actions)"
        lines.append(f"| [{name}]({url}) | {desc} | {topic_badges} | ⭐ {stars} | {ci} |")
    lines.append("")

lines.append("---\n")
lines.append(f"All templates obey [RULES.md](./RULES.md) — discoverable as the `olko:starter-rules` skill via [oleg-koval/agent-skills](https://github.com/oleg-koval/agent-skills).\n")
lines.append("---\n")
lines.append("## How this works\n")
lines.append(f"This README is auto-generated by [`discover.sh`](./discover.sh) using the GitHub GraphQL API.")
lines.append(f"It runs automatically via GitHub Actions on a daily schedule and on every push.\n")
lines.append("To regenerate locally:\n")
lines.append("```bash")
lines.append("./discover.sh")
lines.append("```\n")
lines.append("To add a new repo to this index, simply mark it as a template on GitHub:")
lines.append("```bash")
lines.append(f"gh repo edit {gh_user}/your-repo --template")
lines.append("```\n")
lines.append("---\n")
lines.append(f"*Generated by [oleg-koval/starters](https://github.com/{gh_user}/starters)*")

with open(output_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"  ✓ Written {len(repos)} repos to {output_path}")
PYEOF
