#!/usr/bin/env bash
# discover.sh
# Queries GitHub API for all template repos owned by GH_USER,
# builds README.md. Runs locally and in GitHub Actions CI.

set -euo pipefail

GH_USER="${GH_USER:-oleg-koval}"
OUTPUT="${1:-README.md}"

echo "→ Fetching template repos for $GH_USER..."

# Fetch all repos, filter to templates, sort by updated_at desc
REPOS=$(gh api graphql -f query='
{
  user(login: "'"$GH_USER"'") {
    repositories(first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {
      nodes {
        name
        description
        url
        isTemplate
        updatedAt
        repositoryTopics(first: 10) {
          nodes { topic { name } }
        }
        primaryLanguage { name }
        stargazerCount
        defaultBranchRef {
          target {
            ... on Commit {
              statusCheckRollup { state }
            }
          }
        }
      }
    }
  }
}' --jq '
  .data.user.repositories.nodes
  | map(select(.isTemplate == true))
  | sort_by(.updatedAt)
  | reverse
')

COUNT=$(echo "$REPOS" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")
echo "  Found $COUNT template repos"

# Build README via Python (avoids bash string escaping hell)
python3 - "$REPOS" "$GH_USER" "$OUTPUT" <<'PYEOF'
import json, sys, datetime

repos_json, gh_user, output_path = sys.argv[1], sys.argv[2], sys.argv[3]
repos = json.loads(repos_json)
now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

# CI badge helper
def ci_badge(repo):
    name = repo["name"]
    url  = repo["url"]
    # Common workflow file names
    for wf in ["ci.yml", "code-quality.yml", "test.yml"]:
        badge = f"![CI](https://github.com/{gh_user}/{name}/actions/workflows/{wf}/badge.svg)"
        # We can't verify which file exists from here, use ci.yml as default
    return f"[![CI](https://github.com/{gh_user}/{name}/actions/workflows/ci.yml/badge.svg)]({url}/actions)"

# Language emoji map
LANG_EMOJI = {
    "TypeScript": "🔷",
    "JavaScript": "🟨",
    "Python":     "🐍",
    "Go":         "🐹",
    "Rust":       "🦀",
    "Shell":      "🐚",
}

lines = []
lines.append(f"# starters\n")
lines.append(f"> Auto-generated index of [@{gh_user}](https://github.com/{gh_user}) template repositories.\n")
lines.append(f"> Last updated: {now} · [{len(repos)} templates found](https://github.com/{gh_user}?tab=repositories&q=&type=template)\n")
lines.append("")
lines.append("## Templates\n")

# Group by primary language
from collections import defaultdict
by_lang = defaultdict(list)
for r in repos:
    lang = r.get("primaryLanguage") or {}
    lang_name = lang.get("name") or "Other"
    by_lang[lang_name].append(r)

# Sort languages: TS first, then Go, Python, then rest alphabetically
LANG_ORDER = ["TypeScript", "JavaScript", "Go", "Python", "Rust", "Shell", "Other"]
sorted_langs = sorted(by_lang.keys(), key=lambda l: LANG_ORDER.index(l) if l in LANG_ORDER else 99)

for lang in sorted_langs:
    emoji = LANG_EMOJI.get(lang, "📦")
    lines.append(f"### {emoji} {lang}\n")
    lines.append("| Repo | Description | Topics | Stars | CI |")
    lines.append("|------|-------------|--------|-------|-----|")
    for r in by_lang[lang]:
        name  = r["name"]
        desc  = r.get("description") or ""
        url   = r["url"]
        stars = r.get("stargazerCount", 0)
        topics = [t["topic"]["name"] for t in r.get("repositoryTopics", {}).get("nodes", [])]
        topic_badges = " ".join([f"`{t}`" for t in topics]) if topics else "-"
        ci = f"[![ci]({url}/actions/workflows/ci.yml/badge.svg)]({url}/actions)"
        lines.append(f"| [{name}]({url}) | {desc} | {topic_badges} | ⭐ {stars} | {ci} |")
    lines.append("")

lines.append("---\n")
lines.append("## How this works\n")
lines.append(f"This README is auto-generated by [`discover.sh`](./discover.sh) using the GitHub GraphQL API.")
lines.append(f"It runs automatically via GitHub Actions on a daily schedule and on every push.\n")
lines.append("To regenerate locally:\n")
lines.append("```bash")
lines.append("./discover.sh")
lines.append("```\n")
lines.append("To add a new repo to this index, simply mark it as a template on GitHub:")
lines.append("```bash")
lines.append(f"gh repo edit {gh_user}/your-repo --template")
lines.append("```\n")
lines.append("---\n")
lines.append(f"*Generated by [oleg-koval/starters](https://github.com/{gh_user}/starters)*")

with open(output_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"  ✓ Written {len(repos)} repos to {output_path}")
PYEOF
